"""
Agent-specific schemas for LangGraph state management.
"""

from pydantic import BaseModel, Field
from typing import List, Literal, Optional, TypedDict, Annotated
from langchain_core.messages import BaseMessage


# TypedDict for LangGraph state - this is the core state schema
class GraphState(TypedDict):
    """
    Core state schema for the LangGraph multi-agent workflow.
    
    This state is shared across all agent nodes and tracks:
    - messages: Conversation history with LangChain BaseMessage objects
    - current_error_type: Classification of the math error detected
    - prerequisite_resolved: Whether the knowledge gap has been addressed
    - user_competency_level: Assessment of user's math competency
    - session_id: Unique session identifier
    - current_topic: Current math topic being studied
    """
    messages: Annotated[List[BaseMessage], "Conversation history"]
    current_error_type: Optional[str]
    prerequisite_resolved: bool
    user_competency_level: Literal["beginner", "intermediate", "advanced"]
    session_id: str
    current_topic: Optional[str]
    diagnostic_complete: bool
    socratic_turns: int


class DiagnosticResult(BaseModel):
    """Result from the Diagnostic Agent analysis."""
    
    error_detected: bool = Field(..., description="Whether an error was detected")
    error_type: Optional[str] = Field(None, description="Type of error identified")
    is_prerequisite_gap: bool = Field(
        ..., 
        description="Whether this is a prerequisite knowledge gap"
    )
    missing_concept: Optional[str] = Field(
        None, 
        description="Specific concept that needs remediation"
    )
    confidence: float = Field(
        ..., 
        ge=0.0, 
        le=1.0, 
        description="Confidence score of the diagnosis"
    )
    suggested_routing: Literal["socratic", "direct_answer", "back_to_main"] = Field(
        ..., 
        description="Suggested routing for the conversation flow"
    )
    
    class Config:
        json_schema_extra = {
            "example": {
                "error_detected": True,
                "error_type": "algebraic_manipulation",
                "is_prerequisite_gap": True,
                "missing_concept": "distributive_property",
                "confidence": 0.87,
                "suggested_routing": "socratic"
            }
        }


class SocraticQuery(BaseModel):
    """Query generated by the Socratic Verification Agent."""
    
    question: str = Field(..., description="The probing question to ask the student")
    bloom_level: Literal[
        "remember", 
        "understand", 
        "apply", 
        "analyze", 
        "evaluate", 
        "create"
    ] = Field(..., description="Bloom's Taxonomy level of the question")
    hint_level: int = Field(
        default=0,
        ge=0, 
        le=3, 
        description="Level of hint provided (0 = no hint, 3 = maximum hint)"
    )
    expected_concept: str = Field(
        ..., 
        description="The concept we expect the student to articulate"
    )
    follow_up_strategy: str = Field(
        ..., 
        description="Strategy for follow-up based on student response"
    )
    
    class Config:
        json_schema_extra = {
            "example": {
                "question": "Can you explain what happens when you multiply a number by a sum in parentheses?",
                "bloom_level": "understand",
                "hint_level": 1,
                "expected_concept": "distributive_property",
                "follow_up_strategy": "ask_for_example"
            }
        }
